from fastapi import FastAPI,Form
from fastapi.responses import HTMLResponse
from .database import init_db,connect
from .pricing import PricingInput,calcular_preco
from .fiscal import contexto_fiscal,aliquota_efetiva_cadastrada
app=FastAPI(title='PrecificaEcom'); init_db()
CSS='''body{font-family:Segoe UI,Arial;background:#f4f6f8;margin:0;color:#1f2937}.wrap{max-width:920px;margin:35px auto;padding:0 20px}.card{background:white;padding:24px;border-radius:14px;box-shadow:0 2px 12px #0001;margin-bottom:18px}h1{margin:0 0 5px}.muted{color:#64748b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{display:block;font-size:13px;font-weight:600;margin-bottom:5px}input,select{width:100%;box-sizing:border-box;padding:10px;border:1px solid #cbd5e1;border-radius:8px}button{padding:12px 18px;border:0;border-radius:9px;background:#111827;color:white;font-weight:700;cursor:pointer}.result{font-size:34px;font-weight:800}.warn{padding:12px;background:#fff7ed;border-radius:8px;color:#9a3412}@media(max-width:650px){.grid{grid-template-columns:1fr}}'''
def page(body): return HTMLResponse(f"<!doctype html><html><head><meta charset='utf-8'><title>PrecificaEcom</title><style>{CSS}</style></head><body><div class='wrap'>{body}</div></body></html>")
@app.get('/',response_class=HTMLResponse)
def home():
 con=connect(); emp=con.execute('SELECT * FROM empresa WHERE id=1').fetchone(); regimes=con.execute('SELECT * FROM regimes_tributarios').fetchall(); estados=con.execute('SELECT * FROM estados').fetchall(); con.close()
 ro=''.join(f"<option value='{r['codigo']}' {'selected' if r['codigo']==emp['regime'] else ''}>{r['nome']}</option>" for r in regimes); uo=''.join(f"<option value='{e['uf']}' {'selected' if e['uf']==emp['uf'] else ''}>{e['uf']} - {e['nome']}</option>" for e in estados)
 return page(f'''<div class='card'><h1>PrecificaEcom</h1><p class='muted'>Configuração inicial da empresa</p><form method='post' action='/configurar'><div class='grid'><div><label>Empresa</label><input name='nome' value="{emp['nome']}"></div><div><label>Regime tributário</label><select name='regime'>{ro}</select></div><div><label>UF de origem</label><select name='uf'>{uo}</select></div><div><label>Receita bruta acumulada 12 meses (R$)</label><input type='number' step='.01' name='receita_12m' value="{emp['receita_12m']}"></div></div><br><button>Salvar e precificar</button></form></div>''')
@app.post('/configurar')
def configurar(nome:str=Form(''),regime:str=Form(...),uf:str=Form(...),receita_12m:float=Form(0)):
 con=connect(); con.execute('UPDATE empresa SET nome=?,regime=?,uf=?,receita_12m=? WHERE id=1',(nome,regime,uf,receita_12m)); con.commit(); con.close(); return precificador()
@app.get('/precificar',response_class=HTMLResponse)
def precificador():
 con=connect(); emp=con.execute('SELECT * FROM empresa WHERE id=1').fetchone(); estados=con.execute('SELECT * FROM estados').fetchall(); mods=con.execute('SELECT m.id,m.nome,m.comissao_pct,m.tarifa_fixa,mp.nome marketplace FROM modalidades_venda m JOIN marketplaces mp ON mp.codigo=m.marketplace WHERE m.ativo=1').fetchall(); con.close()
 destinos=''.join(f"<option value='{e['uf']}'>{e['uf']} - {e['nome']}</option>" for e in estados); modalidades=''.join(f"<option value='{m['id']}'>{m['marketplace']} | {m['nome']}</option>" for m in mods)
 return page(f'''<div class='card'><h1>Nova precificação</h1><p class='muted'>Regime: <b>{emp['regime']}</b> | Origem: <b>{emp['uf']}</b></p><form method='post' action='/calcular'><div class='grid'><div><label>NCM</label><input name='ncm' maxlength='8' required placeholder='Ex.: 85171300'></div><div><label>UF de destino</label><select name='uf_destino'>{destinos}</select></div><div><label>Custo do produto (R$)</label><input type='number' step='.01' name='custo' required></div><div><label>Embalagem (R$)</label><input type='number' step='.01' name='embalagem' value='0'></div><div><label>Modalidade de venda</label><select name='modalidade_id'>{modalidades}</select></div><div><label>Modalidade de frete</label><select name='frete_tipo'><option>Frete por conta do comprador</option><option>Frete grátis / vendedor paga</option><option>Subsidiado / compartilhado</option></select></div><div><label>Custo do frete para vendedor (R$)</label><input type='number' step='.01' name='frete' value='0'></div><div><label>Outros custos (R$)</label><input type='number' step='.01' name='outros' value='0'></div><div><label>Ads (% da venda)</label><input type='number' step='.01' name='ads' value='0'></div><div><label>Margem líquida desejada (%)</label><input type='number' step='.01' name='margem' value='15'></div></div><br><button>Calcular preço de venda</button></form></div><div class='warn'>Se não houver regra fiscal validada para o contexto informado, o sistema sinaliza a pendência.</div>''')
@app.post('/calcular',response_class=HTMLResponse)
def calcular(ncm:str=Form(...),uf_destino:str=Form(...),custo:float=Form(...),embalagem:float=Form(0),modalidade_id:int=Form(...),frete_tipo:str=Form(...),frete:float=Form(0),outros:float=Form(0),ads:float=Form(0),margem:float=Form(15)):
 con=connect(); emp=con.execute('SELECT * FROM empresa WHERE id=1').fetchone(); mod=con.execute('SELECT * FROM modalidades_venda WHERE id=?',(modalidade_id,)).fetchone(); con.close(); regras=contexto_fiscal(emp['regime'],emp['uf'],uf_destino,ncm,emp['receita_12m']); imposto=aliquota_efetiva_cadastrada(regras); r=calcular_preco(PricingInput(custo,embalagem,outros,frete,mod['tarifa_fixa'],imposto,mod['comissao_pct'],ads,margem)); pendencia='' if regras else "<div class='warn'>Atenção: nenhuma regra fiscal validada foi encontrada. O imposto usado foi 0%; não use este resultado comercialmente até configurarmos a regra.</div>"
 return page(f'''<div class='card'><h1>Preço recomendado</h1><div class='result'>R$ {r['preco']:.2f}</div><p>NCM: <b>{ncm}</b> | {emp['uf']} → {uf_destino} | Regime: <b>{emp['regime']}</b></p><p>Impostos cadastrados: {imposto:.2f}% | Comissão: {mod['comissao_pct']:.2f}% | Ads: {ads:.2f}%</p><p>Custos fixos: R$ {r['custos_fixos']:.2f} | Impostos: R$ {r['imposto']:.2f} | Comissão: R$ {r['comissao']:.2f} | Lucro: <b>R$ {r['lucro']:.2f}</b></p><p>Margem líquida: <b>{r['margem_real']:.2f}%</b></p><a href='/precificar'>Nova precificação</a></div>{pendencia}''')
